version: "3.9"

services:
  node:
    # image: node:16-alpine
    image: ryusei1226/detected_status_nodejs
    build: 
      context: ./
      dockerfile: Dockerfile.nodejs
    working_dir: /home/node/app
    command: "/bin/sh"
    tty: true
    stdin_open: true
    stop_signal: SIGKILL
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123456
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password123456
    volumes:
      - db-store:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: hever
    ports:
      - 8080:8080

volumes:
  db-store: